'use client';

import { useState, useEffect, useMemo } from 'react';
import {
    TrendingUp, AlertTriangle, Zap, Brain, Target, Building2,
    Lightbulb, ArrowRight,
} from 'lucide-react';
import { getInsights } from '@/lib/api';
import { insightTemplates as fallbackInsights, buildings } from '@/data/mockData';
import styles from './insights.module.css';

const categories = [
    { key: 'all', label: 'All Insights' },
    { key: 'trend', label: '📈 Trends' },
    { key: 'opportunity', label: '💡 Opportunities' },
    { key: 'anomaly', label: '⚠️ Anomalies' },
    { key: 'efficiency', label: '⚡ Efficiency' },
    { key: 'behavioral', label: '🧠 Behavioral' },
    { key: 'prediction', label: '🔮 Predictions' },
];

const categoryIcons = {
    trend: TrendingUp,
    opportunity: Lightbulb,
    anomaly: AlertTriangle,
    efficiency: Zap,
    behavioral: Brain,
    prediction: Target,
};

const severityColors = {
    warning: { bg: 'rgba(251, 191, 36, 0.12)', color: '#fbbf24' },
    positive: { bg: 'rgba(52, 211, 153, 0.12)', color: '#34d399' },
    critical: { bg: 'rgba(248, 113, 113, 0.12)', color: '#f87171' },
    info: { bg: 'rgba(96, 165, 250, 0.12)', color: '#60a5fa' },
};

function getBuildingNameFallback(id) {
    const b = buildings.find(b => b.id === id);
    return b ? b.name : id;
}

export default function InsightsPage() {
    const [activeCategory, setActiveCategory] = useState('all');
    const [insights, setInsights] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        async function loadInsights() {
            setLoading(true);
            try {
                const data = await getInsights(activeCategory);
                setInsights(data);
            } catch (err) {
                console.warn('API unavailable, using fallback:', err.message);
                const filtered = activeCategory === 'all'
                    ? fallbackInsights
                    : fallbackInsights.filter(i => i.category === activeCategory);
                setInsights(filtered.map(i => ({
                    ...i,
                    buildingName: getBuildingNameFallback(i.building),
                    buildingId: i.building,
                })));
            } finally {
                setLoading(false);
            }
        }
        loadInsights();
    }, [activeCategory]);

    return (
        <div className={styles.insights}>
            <div className={styles.header}>
                <h1>🧠 AI Behavioral Insights</h1>
                <p>Intelligent insights and actionable recommendations generated by AI analysis</p>
            </div>

            <div className={styles.filters}>
                {categories.map((cat) => (
                    <button
                        key={cat.key}
                        className={`${styles.filterBtn} ${activeCategory === cat.key ? styles.active : ''}`}
                        onClick={() => setActiveCategory(cat.key)}
                    >
                        {cat.label}
                    </button>
                ))}
            </div>

            <div className={styles.insightsList}>
                {insights.length > 0 ? (
                    insights.map((insight, i) => {
                        const Icon = categoryIcons[insight.category] || Lightbulb;
                        const sev = severityColors[insight.severity] || severityColors.info;
                        return (
                            <div
                                key={insight.id}
                                className={styles.insightCard}
                                style={{
                                    animation: 'fadeInUp 0.5s ease-out forwards',
                                    animationDelay: `${i * 100}ms`,
                                    opacity: 0,
                                }}
                            >
                                <div className={styles.insightTop}>
                                    <div className={styles.insightIcon} style={{ background: sev.bg }}>
                                        <Icon size={20} color={sev.color} />
                                    </div>
                                    <h3 className={styles.insightTitle}>{insight.title}</h3>
                                    <span className={`${styles.categoryTag} ${styles[insight.category]}`}>
                                        {insight.category}
                                    </span>
                                </div>

                                <p className={styles.insightBody}>{insight.insight}</p>

                                <div className={styles.insightRecommendation}>
                                    <div className={styles.recLabel}>💡 Recommendation</div>
                                    {insight.recommendation}
                                </div>

                                <div className={styles.insightFooter}>
                                    <span className={styles.impactTag}>
                                        <ArrowRight size={12} />
                                        {insight.impact}
                                    </span>
                                    <span className={styles.buildingTag}>
                                        <Building2 size={12} />
                                        {insight.buildingName || getBuildingNameFallback(insight.buildingId)}
                                    </span>
                                </div>
                            </div>
                        );
                    })
                ) : (
                    <div className={styles.noResults}>
                        <h3>{loading ? 'Loading...' : 'No insights found'}</h3>
                        <p>{loading ? '' : 'Try a different filter category'}</p>
                    </div>
                )}
            </div>
        </div>
    );
}
